### ISSUE TITLE
Support for Open-Transactions

### ISSUE THREAD

**Issue by baccenfutter** [uwekamper/yeahletsdothat#1]
2014 is suspected to be the year of open-transactions. Open-Transactions is a crypto-currency back-end, such as you would require to run a platform like Mt. Gox, with several additional conveniences. Their slogen: "We bring democracy to currency!"

I would gladly appreciate if yeahletsdothat would support Open-Transactions as a back-end. One benefit could be, that OT already has built-in support for BTC. Another one would be, that yeahletsdothat would be independent from specific crypto-currencies and could adjust to the crypto-currency-market dynamically.

**Comment by uwekamper** [comment]
@baccenfutter Ist das noch aktuell? Oder kann ich das Ticket als "wontfix" schließen?

**Comment by baccenfutter** [comment]
Ich kann mich ehrlich gesagt, nicht mal mehr erinnern es aufgemacht zu haben. Nach nunmehr fasy zwei Jahren macht das Projekt auf mich auf eher den Eindruck, als wolle es in eine andere Richtung ziehen (mehr als nur Spielkram fuer die base).
